HomeMVC/Models/TV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeMVC
{
    public class TV : Devices, ISwitchbl, ISetChannel, ISetVolume
    {
        private byte channel = 1;
        private SetLevel volume = SetLevel.Low;
        public TV(string viewPath, string name) : base(viewPath, name)
        {
        }
        public SetLevel Volume
        {
            get
            {
                return volume;
            }
        }
        public byte Chennel
        {
            get
            {
                return channel;
            }
        }
        public void OnOff()
        {
            if (State)
            {
                state = false;
                volume = SetLevel.Low;
                return;
            }
            if (!State)
            {
                state = true;
                return;
            }
        }
        public void ChannelUp()
        {
            if (10 > channel)
            {
                channel++;
            }
            if (10 == channel)
            {
                channel = 1;
            }
        }
        public void ChannelDown()
        {
            if (1 < channel)
            {
                channel--;
            }
            if (1 == channel)
            {
                channel = 10;
            }
        }
        public void VolumeUp()
        {
            if (volume == SetLevel.Medium && state)
            {
                volume = SetLevel.Height;
                return;
            }
            else if (volume == SetLevel.Low && state)
            {
                volume = SetLevel.Medium;
                return;
            }
        }
        public void VolumeDown()
        {
            if (volume == SetLevel.Medium && state)
            {
                volume = SetLevel.Low;
                return;
            }
            else if (volume == SetLevel.Height && state)
            {
                volume = SetLevel.Medium;
                return;
            }
        }
    }
}

HomeMVC/Controllers/TVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeMVC
{
    public class TVController : Controller
    {
        // GET: TV
        private IDictionary<string, Devices> deviceList;
        public ActionResult TVViwe()
        {
            return View();
        }
        public ActionResult OnOff(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((ISwitchbl)deviceList[name]).OnOff();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult ChannelDown(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((TV)deviceList[name]).ChannelDown();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult ChannelUp(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((TV)deviceList[name]).ChannelUp();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult VolumeDown(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((TV)deviceList[name]).VolumeDown();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult VolumeUp(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((TV)deviceList[name]).VolumeUp();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Delete(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            deviceList.Remove(name);
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
    }
}

HomeMVC/Views/TV/TVViwe.cshtml
@model HomeMVC.TV
@{
    Layout = null;
}
<div class="_devices">
    <span class="_panelName">@Model.Name</span>
    @{
        if (Model.State)
        {
            <span class="_paneState">On</span>
        }
        else
        {
            <span class="_paneState">Off</span>
        }
    }
    <button type="button" class="_buttonDelete" onclick="location.href='@Url.Action("Delete", "TV", new { name = @Model.Name} )'">X</button>
    @{
        if (!Model.State)
        {
            <img src="~/Content/Picture/TVoff.jpg" class="_tvImage" />
        }
        else
        {
            switch (Model.Chennel)
            {
                default:
                    break;
                case 1:
                    <img src="~/Content/Picture/1.gif" class="_tvImage" />
                    break;
                case 2:
                    <img src="~/Content/Picture/2.gif" class="_tvImage" />
                    break;
                case 3:
                    <img src="~/Content/Picture/3.gif" class="_tvImage" />
                    break;
                case 4:
                    <img src="~/Content/Picture/4.gif" class="_tvImage" />
                    break;
                case 5:
                    <img src="~/Content/Picture/5.gif" class="_tvImage" />
                    break;
                case 6:
                    <img src="~/Content/Picture/6.gif" class="_tvImage" />
                    break;
                case 7:
                    <img src="~/Content/Picture/7.gif" class="_tvImage" />
                    break;
                case 8:
                    <img src="~/Content/Picture/8.gif" class="_tvImage" />
                    break;
                case 9:
                    <img src="~/Content/Picture/9.gif" class="_tvImage" />
                    break;
                case 10:
                    <img src="~/Content/Picture/10.gif" class="_tvImage" />
                    break;
            }
        }
    }
    <button type="button" class="_tvButtons" onclick="location.href='@Url.Action("OnOff", "TV", new { name = @Model.Name} )'">OnOff</button>
    <button type="button" class="_tvButtons" onclick="location.href='@Url.Action("ChannelDown", "TV", new { name = @Model.Name })'">Ch <</button>
    <button type="button" class="_tvButtons" onclick="location.href='@Url.Action("ChannelUp", "TV", new { name = @Model.Name })'">> Ch</button>
    <button type="button" class="_tvButtonVolume" onclick="location.href='@Url.Action("VolumeDown", "TV", new { name = @Model.Name })'">V <</button>
    <button type="button" class="_tvButtonVolume" onclick="location.href='@Url.Action("VolumeUp", "TV", new { name = @Model.Name })'">> V</button>
    @{
        if (!Model.State)
        {
            <span class="_tvPanelVolume">Volume</span>
        }
        else
        {
            if (Model.Volume == SetLevel.Low)
            {
                <span class="_tvPanelVolume">Volume - Low</span>
            }
            else if (Model.Volume == SetLevel.Medium)
            {
                <span class="_tvPanelVolume">Volume - Medium</span>
            }
            else if (Model.Volume == SetLevel.Height)
            {
                <span class="_tvPanelVolume">Volume - Height</span>
            }
        }
    }
</div>