HomeMVC/Models/Bake.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeMVC
{
    public class Bake : Devices
    {
        private IDictionary<string, Devices> burnerList;
        private Oven bakeOven;
        public Bake(string viewPath, string name, IDictionary<string, Devices> burnerList, Oven bakeOven) : base(viewPath, name)
        {
            this.burnerList = new Dictionary<string, Devices>();
            this.burnerList = burnerList;
            this.bakeOven = bakeOven;
        }
        public IDictionary<string, Devices> GetBurnerList()
        {
            return burnerList;
        }
        public Oven GetBakeOven()
        {
            return bakeOven;
        }
    }
}

HomeMVC/Controllers/BakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeMVC
{
    public class BakeController : Controller
    {
        // GET: Bake
        private string parentName;
        private IDictionary<string, Devices> deviceList;
        private IDictionary<string, Devices> burnerList;
        private Oven bakeOven;
        public ActionResult BakeView()
        {
            parentName = ViewBag.ParentName;
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            burnerList = ((Bake)deviceList[parentName]).GetBurnerList();
            ViewBag.BurnerList = burnerList;
            bakeOven = ((Bake)deviceList[parentName]).GetBakeOven();
            ViewBag.BakeOven = bakeOven;
            return View();
        }
        public ActionResult Delete(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            deviceList.Remove(name);
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
    }
}

HomeMVC/Views/Bake/BakeView.cshtml
@model HomeMVC.Bake
@{
    Layout = null;
}
<div class="_devices">
    <span class="_bakePanelName">@Model.Name</span>
    <button type="button" class="_buttonDelete" onclick="location.href='@Url.Action("Delete", "Bake", new { name = @Model.Name} )'">X</button>
    @{
        foreach (var burner in ((IDictionary<string, Devices>)Model.GetBurnerList()))
        {
            Html.RenderPartial(burner.Value.ViewPath, burner.Value);
        }
    }
    @{
        Html.RenderPartial(((Oven)Model.GetBakeOven()).ViewPath, ((Oven)Model.GetBakeOven()));
    }
</div>