HomeMVC/Models/Frige.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeMVC
{
    public class Frige : Devices, ISwitchbl, ISetLevel
    {
        private Lamp lamp;
        private SetLevel frigeLevel = SetLevel.Low;
        public Frige() { }
        public Frige(string viewPath, string name, Lamp lamp) : base(viewPath, name)
        {
            this.lamp = lamp;
        }
        public SetLevel FrigeLevel
        {
            get
            {
                return frigeLevel;
            }
        }
        public void LampOnOff()
        {
            lamp.OnOff();
        }
        public bool GetLampState()
        {
            return lamp.State;
        }
        public void OnOff()
        {
            if (State)
            {
                state = false;
                return;
            }
            if (!State)
            {
                state = true;
                return;
            }
        }
        public void LevelUp()
        {
            if (frigeLevel == SetLevel.Medium && state)
            {
                frigeLevel = SetLevel.Height;
                return;
            }
            else if (frigeLevel == SetLevel.Low && state)
            {
                frigeLevel = SetLevel.Medium;
                return;
            }
        }
        public void LevelDown()
        {
            if (frigeLevel == SetLevel.Medium && state)
            {
                frigeLevel = SetLevel.Low;
                return;
            }
            else if (frigeLevel == SetLevel.Height && state)
            {
                frigeLevel = SetLevel.Medium;
                return;
            }
        }
    }
}

HomeMVC/Controllers/FrigeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeMVC
{
    public class FrigeController : Controller
    {
        // GET: Frige
        private IDictionary<string, Devices> deviceList;
        public ActionResult FrigeView()
        {
            return View();
        }
        public ActionResult OnOff(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((ISwitchbl)deviceList[name]).OnOff();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LampOnOff(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((Frige)deviceList[name]).LampOnOff();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LevelDown(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((Frige)deviceList[name]).LevelDown();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LevelUp(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            ((Frige)deviceList[name]).LevelUp();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Delete(string name)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            deviceList.Remove(name);
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
    }
}

HomeMVC/Views/Frige/FrigeView.cshtml
@model HomeMVC.Frige
@{
    Layout = null;
}
<div class="_devices">
    <span class="_panelName">@Model.Name</span>
    @{
        if (Model.State)
        {
            <span class="_paneState">On</span>
        }
        else
        {
            <span class="_paneState">Off</span>
        }
    }
    <button type="button" class="_buttonDelete" onclick="location.href='@Url.Action("Delete", "Frige", new { name = @Model.Name} )'">X</button>
    <img src="~/Content/Picture/Frige.jpg" class="_frigeImage" />
    <button type="button" class="_frigeButtonOnOff" onclick="location.href='@Url.Action("OnOff", "Frige", new { name = @Model.Name} )'">OnOff</button>
    @{
        if (Model.GetLampState())
        {
            <span class="_frigePanelLampState">Lamp On</span>
        }
        else
        {
            <span class="_frigePanelLampState">Lamp Off</span>
        }
}
    <button type="button" class="_frigeButtonOnOff" onclick="location.href='@Url.Action("LampOnOff", "Frige", new { name = @Model.Name })'">OnOff</button>
    <button type="button" class="_frigeButtonFrizingLevel" onclick="location.href='@Url.Action("LevelDown", "Frige", new { name = @Model.Name })'"><</button>
    <button type="button" class="_frigeButtonFrizingLevel" onclick="location.href='@Url.Action("LevelUp", "Frige", new { name = @Model.Name })'">></button>
    @{
        if (!Model.State)
        {
            <span class="_frigePanelFrizingLevel">Frizing level</span>
        }
        else if (Model.State && Model.FrigeLevel == SetLevel.Low)
        {
            <span class="_frigePanelFrizingLevel">Frizing level - Low</span>
        }
        else if (Model.State && Model.FrigeLevel == SetLevel.Medium)
        {
            <span class="_frigePanelFrizingLevel">Frizing level - Medium</span>
        }
        else if (Model.State && Model.FrigeLevel == SetLevel.Height)
        {
            <span class="_frigePanelFrizingLevel">Frizing level - Height</span>
        }
    }
</div>