HomeMVC/Models/Burner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeMVC
{
    public class Burner : Devices, ISwitchbl, ISetLevel
    {
        private SetLevel burnLevel;
        public Burner(string viewPath, string parentName, string name) : base(viewPath, parentName, name)
        {
        }
        public SetLevel BurnerLevel
        {
            get
            {
                return burnLevel;
            }
        }
        public void OnOff()
        {
            if (State)
            {
                state = false;
                return;
            }
            if (!State)
            {
                state = true;
                return;
            }
        }
        public void LevelUp()
        {
            if (burnLevel == SetLevel.Medium && state)
            {
                burnLevel = SetLevel.Height;
                return;
            }
            else if (burnLevel == SetLevel.Low && state)
            {
                burnLevel = SetLevel.Medium;
                return;
            }
        }
        public void LevelDown()
        {
            if (burnLevel == SetLevel.Medium && state)
            {
                burnLevel = SetLevel.Low;
                return;
            }
            else if (burnLevel == SetLevel.Height && state)
            {
                burnLevel = SetLevel.Medium;
                return;
            }
        }
    }
}

HomeMVC/Controllers/BurnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeMVC
{
    public class BurnerController : Controller
    {
        // GET: Burner
        private IDictionary<string, Devices> deviceList;
        private IDictionary<string, Devices> burnerList;
        public ActionResult BurnerView()
        {
            return View();
        }
        public ActionResult OnOff(string name, string parentName)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            burnerList = ((Bake)deviceList[parentName]).GetBurnerList();
            ((ISwitchbl)burnerList[name]).OnOff();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LevelDown(string name, string parentName)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            burnerList = ((Bake)deviceList[parentName]).GetBurnerList();
            ((ISetLevel)burnerList[name]).LevelDown();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LevelUp(string name, string parentName)
        {
            deviceList = (Dictionary<string, Devices>)Session["Device"];
            burnerList = ((Bake)deviceList[parentName]).GetBurnerList();
            ((ISetLevel)burnerList[name]).LevelUp();
            Session["Device"] = deviceList;
            return RedirectToAction("Index", "Home");
        }
    }
}

HomeMVC/Views/Burner/BurnerView.cshtml
@model HomeMVC.Burner
@{
    Layout = null;
}
<div class="_burners">
    @{
        if (Model.State)
        {
            <span class="_burnerPanelState">On</span>
        }
        else
        {
            <span class="_burnerPanelState">Off</span>
        }
        if (!Model.State)
        {
            <img src="~/Content/Picture/BurnerOff.jpg" class="_burnerImage" />
        }
        else if (Model.State && Model.BurnerLevel == SetLevel.Low)
        {
            <img src="~/Content/Picture/BurnerLow.jpg" class="_burnerImage" />
        }
        else if (Model.State && Model.BurnerLevel == SetLevel.Medium)
        {
            <img src="~/Content/Picture/BurnerMedium.jpg" class="_burnerImage" />
        }
        else if (Model.State && Model.BurnerLevel == SetLevel.Height)
        {
            <img src="~/Content/Picture/BurnerHeight.jpg" class="_burnerImage" />
        }
    }
    <button type="button" class="_burnerButtonOnOff" onclick="location.href='@Url.Action("OnOff", "Burner", new { name = @Model.Name, parentName = @Model.ParentName } )'">OnOff</button>
    <button type="button" class="_burnerButtonLevel" onclick="location.href='@Url.Action("LevelDown", "Burner", new { name = @Model.Name, parentName = @Model.ParentName })'"><</button>
    <button type="button" class="_burnerButtonLevel" onclick="location.href='@Url.Action("LevelUp", "Burner", new { name = @Model.Name, parentName = @Model.ParentName })'">></button>
</div>
    